### ISSUE TITLE
Global patch on pathlib module breaks 3rd party library ruamel.yaml

### ISSUE THREAD

**Issue by parano** [fastai/fastcore#29] opened 2020-04-23 01:20 UTC
hi - while helping @HenryDashwood to get his work on support fastai2 in BentoML(https://github.com/bentoml/BentoML/pull/596), we noticed an issue that is unique to fastai2, here are the code to reproduce the issue:

Install `fastcore` and `ruamel.yaml`, the following code should run without any issue:
```python
conda_env_yaml = """
name: bentoml-Demo
channels:
  - defaults
dependencies:
  - python=3.7.5
  - pip
"""
from ruamel.yaml import YAML
yaml = YAML()
y = yaml.load(conda_env_yaml)
from pathlib import Path
yaml.dump(y, Path("/tmp/test.yml"))
```
But after importing `fastcore.utils` with `from fastcore.utils import *` and run the code above again, the follow error occurs:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-beaac7fd8e8a> in <module>
     11 y = yaml.load(conda_env_yaml)
     12 from pathlib import Path
---> 13 yaml.dump(y, Path("/tmp/test.yml"))

~/opt/miniconda3/envs/btml-dev/lib/python3.7/site-packages/ruamel/yaml/main.py in dump(self, data, stream, _kw, transform)
    447             if stream is None:
    448                 raise TypeError('Need a stream argument when not dumping from context manager')
--> 449             return self.dump_all([data], stream, _kw, transform=transform)
    450
    451     def dump_all(self, documents, stream, _kw=enforce, transform=None):

~/opt/miniconda3/envs/btml-dev/lib/python3.7/site-packages/ruamel/yaml/main.py in dump_all(self, documents, stream, _kw, transform)
    461         self._context_manager = YAMLContextManager(self, transform=transform)
    462         for data in documents:
--> 463             self._context_manager.dump(data)
    464         self._context_manager.teardown_output()
    465         self._output = None

~/opt/miniconda3/envs/btml-dev/lib/python3.7/site-packages/ruamel/yaml/main.py in dump(self, data)
    813             self.init_output(data)
    814         try:
--> 815             self._yaml.representer.represent(data)
    816         except AttributeError:
    817             # nprint(dir(dumper._representer))

~/opt/miniconda3/envs/btml-dev/lib/python3.7/site-packages/ruamel/yaml/representer.py in represent(self, data)
     84         # type: (Any) -> None
     85         node = self.represent_data(data)
---> 86         self.serializer.serialize(node)
     87         self.represented_objects = {}
     88         self.object_keeper = []

~/opt/miniconda3/envs/btml-dev/lib/python3.7/site-packages/ruamel/yaml/serializer.py in serialize(self, node)
    115         )
    116         self.anchor_node(node)
--> 117         self.serialize_node(node, None, None)
    118         self.emitter.emit(DocumentEndEvent(explicit=self.use_explicit_end))
    119         self.serialized_nodes = {}

~/opt/miniconda3/envs/btml-dev/lib/python3.7/site-packages/ruamel/yaml/serializer.py in serialize_node(self, node, parent, index)
    230                 )
    231                 for key, value in node.value:
--> 232                     self.serialize_node(key, node, None)
    233                     self.serialize_node(value, node, key)
    234                 self.emitter.emit(MappingEndEvent(comment=[map_comment, end_comment]))

~/opt/miniconda3/envs/btml-dev/lib/python3.7/site-packages/ruamel/yaml/serializer.py in serialize_node(self, node, parent, index)
    178                         node.value,
    179                         style=node.style,
--> 180                         comment=node.comment,
    181                     )
    182                 )

~/opt/miniconda3/envs/btml-dev/lib/python3.7/site-packages/ruamel/yaml/emitter.py in emit(self, event)
    252         while not self.need_more_events():
    253             self.event = self.events.pop(0)
--> 254             self.state()
    255             self.event = None
    256

~/opt/miniconda3/envs/btml-dev/lib/python3.7/site-packages/ruamel/yaml/emitter.py in expect_first_block_mapping_key(self)
    662     def expect_first_block_mapping_key(self):
    663         # type: () -> None
--> 664         return self.expect_block_mapping_key(first=True)
    665
    666     def expect_block_mapping_key(self, first=False):

~/opt/miniconda3/envs/btml-dev/lib/python3.7/site-packages/ruamel/yaml/emitter.py in expect_block_mapping_key(self, first)
    687                         pass
    688                 self.states.append(self.expect_block_mapping_simple_value)
--> 689                 self.expect_node(mapping=True, simple_key=True)
    690                 if isinstance(self.event, AliasEvent):
    691                     self.stream.write(u' ')

~/opt/miniconda3/envs/btml-dev/lib/python3.7/site-packages/ruamel/yaml/emitter.py in expect_node(self, root, sequence, mapping, simple_key)
    420             if isinstance(self.event, ScalarEvent):
    421                 # nprint('@', self.indention, self.no_newline, self.column)
--> 422                 self.expect_scalar()
    423             elif isinstance(self.event, SequenceStartEvent):
    424                 # nprint('@', self.indention, self.no_newline, self.column)

~/opt/miniconda3/envs/btml-dev/lib/python3.7/site-packages/ruamel/yaml/emitter.py in expect_scalar(self)
    468         # type: () -> None
    469         self.increase_indent(flow=True)
--> 470         self.process_scalar()
    471         self.indent = self.indents.pop()
    472         self.state = self.states.pop()

~/opt/miniconda3/envs/btml-dev/lib/python3.7/site-packages/ruamel/yaml/emitter.py in process_scalar(self)
    883             self.write_literal(self.analysis.scalar, self.event.comment)
    884         else:
--> 885             self.write_plain(self.analysis.scalar, split)
    886         self.analysis = None
    887         self.style = None

~/opt/miniconda3/envs/btml-dev/lib/python3.7/site-packages/ruamel/yaml/emitter.py in write_plain(self, text, split)
   1614                         data = data.encode(self.encoding)
   1615                     try:
-> 1616                         self.stream.write(data)
   1617                     except:  # NOQA
   1618                         sys.stdout.write(repr(data) + '\n')

~/opt/miniconda3/envs/btml-dev/lib/python3.7/site-packages/fastcore/utils.py in write(self, txt, encoding)
    428     "Write `txt` to `self`, creating directories as needed"
    429     self.parent.mkdir(parents=True,exist_ok=True)
--> 430     with self.open('w', encoding=encoding) as f: f.write(txt)
    431
    432 # Cell

TypeError: write() argument must be str, not bytes
```

After looking into this, the reason was the following code in the fastcore/utils.py file: https://github.com/fastai/fastcore/blob/8a56bcbb2be3d5a2ab137b312c981a31d50f5cbe/fastcore/utils.py#L480

```
@patch
def write(self:Path, txt, encoding='utf8'):
    "Write `txt` to `self`, creating directories as needed"
    self.parent.mkdir(parents=True,exist_ok=True)
    with self.open('w', encoding=encoding) as f: f.write(txt)
```

The code is adding a global patch to the `pathlib.Path` object, this line specifically added the method "write" to Path. However `ruamel.yaml`, a popular YAML handling library for python, is depending on this attribute missing, to tell if the given file path is a `pathlib.Path` object:
https://github.com/pycontribs/ruamel-yaml/blob/7692648298f680357e09502f991ce0d1c213bfeb/main.py#L755

This made it very hard to integrate fastai2 with BentoML for model serving, or for anything that uses `ruamel.yaml`. It may break other packages too. I think in general libraries should avoid this type of global patching especially on core modules like pathlib.

**Comment by KushajveerSingh** [comment] 2020-04-23 08:11
The problem is not with global patching. By default, fastcore saves the object with utf-8 encoding, but the above error means that the object should be saved as a binary object. So I changed the following lines and the error is resolved.

```python
# Original (in write function of utils.py)
with self.open('w', encoding=encoding) as f: f.write(txt)

# Change the above line to
with self.open('wb') as f: f.write(txt)
```

To integrate the above change to fastcore, I think the solution would be to use `try-except` statement, as it would not change the functionality of any fastcore module.

The below code solves the problem.
```python
@patch
def write(self:Path, txt, encoding='utf8'):
    "Write `txt` to `self`, creating directories as needed"
    self.parent.mkdir(parents=True,exist_ok=True)
    try:  
        with self.open('w', encoding=encoding) as f: f.write(txt)
    except TypeError: 
        with self.open('wb') as f: f.write(txt)
```

However, input from @sgugger is needed on how this needs to be integrated into fastcore. I can submit a PR if needed.

**Comment by sgugger** [comment] 2020-04-23 11:37
> It may break other packages too. I think in general libraries should avoid this type of global patching especially on core modules like pathlib.

I personally think it is rather silly to check if something is an instance of `pathlib.Path` by checking if it has some attributes instead of using `isinstance(o, Path)` but I may be missing some context into why it is done this way. Patching things is one of the great ways in python to add some missing behavior + what if one day a write method is indeed added to `Pathlib` objectcs?

In any case, if there is a way to fix this error internally, I can review any PR. It is very unlikely we will remove this (or stop adding useful methods to objects of other libraries).

**Comment by KushajveerSingh** [comment] 2020-04-23 14:46
How do you want to solve this issue? I can think of 3 ways in which this can be done:
1. Let the user write his own write function and replace the fastcore `write` function.
2. Use a try-catch statement as I did in the above comment.
3. Add a `mode` argument to the write function. And depending on the value of it save the file.

```python
# for option 3
@patch
def write(self:Path, txt, encoding='utf8', mode=None):
    "Write `txt` to `self`, creating directories as needed"
    self.parent.mkdir(parents=True,exist_ok=True)
    if mode is None:
        with self.open('w', encoding=encoding) as f: f.write(txt)
    elif mode == 'binary': 
        with self.open('wb') as f: f.write(txt)
```

**Comment by KushajveerSingh** [comment] 2020-04-23 15:59
Do you want to make changes to resolve this issue, as this issue is specific to a library and the change is more suited to be made in that library?

The reason for the above statement is that this would also require to change the `read` function. I tested the `read` function and it results in an infinite loop for some when loading the saved yaml object.

Also, if this issue has to be resolved it can be easily done by deleting `write`, `read`, `readlines` attributes of the `pathlib.Path` class. So using the below lines in the code solves the issue:

```python
from ruamel.yaml import YAML
from fastcore.all import *

delattr(Path, 'write')
delattr(Path, 'read')
delattr(Path, 'readlines')

yaml.dump(y, Path("test.yml")) # This line works now
```

**Comment by parano** [comment] 2020-04-23 17:18
@sgugger the reason `ruamel.yaml` did it that way was for supporting python2. `pathlib` was introduced in python3.4 and libraries supporting both python2 and 3 use other implementations such as [pathlib2](https://github.com/mcmtroffaes/pathlib2) or other custom pathlib implementation under python2. This way `ruamel.yaml` works with all those `pathlib` variations as long as they follow the same interface as the builtin pathlib. If pathlib actually added a `write` method one day and its signature or implementation were different than the code in fastcore, fastcore will have to change as well right?

I'd recommend patch it within the fastai project's scope, something like this would work:
```python
# fastai.util.path.py
from pathlib import Path as BuiltinPath

class Path(BuiltinPath):
     def write(self, text, encoding="utf-8"):
         ...
```
In other fastai code, replace `from pathlib import Path` with:
```
from fastcore.util.path import Path
```

Happy to help make this contribution either this way or the `try ... except ...` approach @KushajveerSingh provided above if we can get consensus, let me know what you think.

Thanks!

**Comment by parano** [comment] 2020-04-23 17:30
Personally I'd prefer an approach that avoids patch and replace it with a utility function. e.g.:

```python
# fastai.util.path.py
def write(path:Path, text, encoding="utf-8"):
      ...
```
and replace usages like `path.write(text)`  with:
```
from fastcore.util.path import write
write(path, text)
```

**Comment by parano** [comment] 2020-04-23 17:37
To fix this error internally 
```
@patch
def write(self:Path, txt, encoding='utf8'):
    "Write `txt` to `self`, creating directories as needed"
    self.parent.mkdir(parents=True,exist_ok=True)
    return self.write_text(self, )

```

> Do you want to make changes to resolve this issue, as this issue is specific to a library and the change is more suited to be made in that library?
> 
> The reason for the above statement is that this would also require to change the `read` function. I tested the `read` function and it results in an infinite loop for some reason when loading the saved yaml object.
> 
> Also, if this issue has to be resolved it can be easily done by deleting `write`, `read`, `readlines` attributes of the `pathlib.Path` class. So using the below lines in the code solves the issue:
> 
> ```python
> from ruamel.yaml import YAML
> from fastcore.all import *
> 
> delattr(Path, 'write')
> delattr(Path, 'read')
> delattr(Path, 'readlines')
> 
> yaml.dump(y, Path("test.yml")) # This line works now
> ```

That will break some other fastai/fastcore functionality right?

**Comment by KushajveerSingh** [comment] 2020-04-23 18:08
> That will break some other fastai/fastcore functionality right?
I don't know exactly. Just for reference, there are three functions that I suggested to delete:
1. `write` :- you can replace this function with the `try-except` version and you are good to go
2. `readlines` :- I don't think this function is much used, so you can ignore it.
3. `read` :- Yeah this will get affected. But the sole reason being I have not yet gone through the source code of why this function is not working with `ruamel.yaml`. When I tested this function it was an infinite loop or something but I did not dig into it much. So maybe with some work, the problem can be found and then just a refractoring of the code.

**Comment by sgugger** [comment] 2020-04-23 18:20
I maintain that the problem does not come from fastcore but from the way the test is done `ruamel.yaml`. Relying on attributes in a dynamic language like Python is dangerous, for the reason we are seeing with this bug, and the test should test for actual pathlib or pathlib2 objects by having imports conditioned on a version of python.

Saying you should never patch things in a language that lets you do that is like saying you should never use the word "the" in English.

Instead of wanting us to change our code, you can simply import the original `Path` before import fastai2 like such:
```
from pathlib import Path as BasePath
```
and then use this one (or plain strings...) in `ruamel.yaml`.

I am closing this issue as a result.

**Closed by sgugger** 2020-04-23 18:20 UTC

**Comment by parano** [comment] 2020-04-23 18:40
@sgugger thanks for the reply - yes I'm all for using patch but I think it should only be applied in a local scope. 

Unfortunately, I don't think this workaround(importing original before importing fastai2) will work, because the fastcore patch is modifying the same loaded module in memory that `BasePath` in your example code is pointing to.

![Screen Shot 2020-04-23 at 11 34 46 AM](https://user-images.githubusercontent.com/489344/80136367-71bb3f80-8556-11ea-9f95-fd74b183b776.png)

I can probably avoid the error by deleting those attributes and adding back afterward in my code. Hope this thread is helpful for others.

**Comment by sgugger** [comment] 2020-04-23 19:17
Ah, I see. Is that what you meant with your workaround (cause that would still make Path have a write attribute, but pathlib.Path would be untouched)?

**Comment by parano** [comment] 2020-04-23 19:33
@sgugger yes that's what I mean, with that workaround, all fastai code can still use the patched Path, where `pathlib.Path` remains untouched.

**Comment by sgugger** [comment] 2020-04-23 19:40
Ok, the problem is then that subclassing `Path` is next to impossible: if I do something like:
```
from pathlib.Path import Path as BasePath
Path = class(BasePth): pass
```
I then get problems when using it (specific error is that it has no `_flavour`).

I'm open to do this subclass to contain the patching, but I remember spending hours trying to have subclasses of `Path` a while ago without succeeding...

**Comment by sgugger** [comment] 2020-04-24 19:54
Added a context manager, you should now be able to do:
```python
with remove_patches_path():
    yaml.dump(y, Path("/tmp/test.yml"))
```
and it should work.

**Comment by parano** [comment] 2020-04-24 20:21
@sgugger awesome, thanks for adding this!

**Comment by domdfcoding** [comment] 2020-09-05 16:57
`pathlib.Path` has a hardcoded check in `__new__` for `cls` being `pathlib.Path`. In a subclass that is False, so it assumes that `cls` is instead one of the flavours of Path. Is is possible to create a subclass of Path, but it requires a bit more work:

```python
import os
import pathlib


class FastCorePath(pathlib.Path):
	"""Subclass of pathlib.Path with extra fastcore methods.

	Path represents a filesystem path but unlike PurePath, also offers
	methods to do system calls on path objects. Depending on your system,
	instantiating a Path will return either a PosixPath or a WindowsPath
	object. You can also instantiate a PosixPath or WindowsPath directly,
	but cannot instantiate a WindowsPath on a POSIX system or vice versa.
	"""

	def __new__(cls, *args, **kwargs):
		if cls is FastCorePath:
			cls = PosixFastCorePath if os.name == 'nt' else WindowsFastCorePath

		self = cls._from_parts(args, init=False)  # type: ignore
		if not self._flavour.is_supported:
			raise NotImplementedError(f"cannot instantiate {cls.__name__!r} on your system")

		self._init()
		return self


class PosixFastCorePath(FastCorePath, pathlib.PurePosixPath):
	"""Path subclass for non-Windows systems.

	On a POSIX system, instantiating a FastCorePath object should return an instance of this class.
	"""
	__slots__ = ()


class WindowsFastCorePath(FastCorePath, pathlib.PureWindowsPath):
	"""Path subclass for Windows systems.

	On a Windows system, instantiating a FastCorePath object should return an instance of this class.
	"""
	__slots__ = ()

	def owner(self):
		raise NotImplementedError("Path.owner() is unsupported on this system")

	def group(self):
		raise NotImplementedError("Path.group() is unsupported on this system")

	def is_mount(self):
		raise NotImplementedError("Path.is_mount() is unsupported on this system")

```

Adding the fastcore-specific methods to `FastCorePath` will also make them available in `PosixFastCorePath` and `WindowsFastCorePath`. Fastcore can then use this class internally without monkeypatching `pathlib.Path`

I have been using a subclass created in this way for a while now without issue.
