### ISSUE TITLE
Latest FASTCORE version error: TypeError: patch() got an unexpected keyword argument 'as_prop'

### ISSUE THREAD

**Issue by tkravichandran** [fastai/fastcore#177] opened 2020-11-07 21:11 UTC
Please confirm you have the latest versions of fastai, fastcore, fastscript, and nbdev prior to reporting a bug (delete one): YES (fastscript is deprecated according to [here](https://github.com/fastai/fastscript), nbdev deosn't seem relevant for this error)

**Describe the bug**
*Disclaimer:* No errors today morning. But get errors (shown below) now. I have not done anything other than open and work with the nbs in fastbook (within Gradient). No installation Nothing.

When I run `from fastai.vision.all import *` (in a gradient fastai container notebook) I get the following error `TypeError: patch() got an unexpected keyword argument 'as_prop'`

When I run the same in a terminal (in a gradient fastai container notebook) I get the following error `ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.22' not found (required by /opt/conda/envs/fastai/lib/python3.8/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-38-x86_64-linux-gnu.so)`, But `libstdc++6` is already the newest version in the container.

**How I "solved" it for now?**
Downgraded `fastcore` to `1.3.1` from `1.3.2` and no more error (`pip install fastcore==1.3.1`)

**Additional context**
I had the suspicion that it could be due to `fastcore 1.3.2` whose new version was released only 22 hrs back. Gradient has the latest fastcore and fastai packages (2.1.4 and 1.3.2)

**To Reproduce**
1. Run `from fastai.vision.all import *` (I ran it in gradient notebook)

**Error with full stack trace**

`from fastai.vision.all import *` (in a gradient fastai container notebook)
`TypeError: patch() got an unexpected keyword argument 'as_prop'`

```
TypeError                                 Traceback (most recent call last)
<ipython-input-8-a1486c4587cf> in <module>
      1 #hide
----> 2 from fastai.vision.all import *
      3 from fastbook import *
      4 
      5 matplotlib.rc('image', cmap='Greys')

/opt/conda/envs/fastai/lib/python3.8/site-packages/fastai/vision/all.py in <module>
      1 from . import models
      2 from ..basics import *
----> 3 from ..callback.all import *
      4 from .augment import *
      5 from .core import *

/opt/conda/envs/fastai/lib/python3.8/site-packages/fastai/callback/all.py in <module>
      3 from .fp16 import *
      4 from .hook import *
----> 5 from .mixup import *
      6 from .progress import *
      7 from .schedule import *

/opt/conda/envs/fastai/lib/python3.8/site-packages/fastai/callback/mixup.py in <module>
      6 from ..basics import *
      7 from .progress import *
----> 8 from ..vision.core import *
      9 from ..vision.models.xresnet import *
     10 

/opt/conda/envs/fastai/lib/python3.8/site-packages/fastai/vision/core.py in <module>
     23 if not hasattr(Image,'_patched'):
     24     _old_sz = Image.Image.size.fget
---> 25     @patch(as_prop=True)
     26     def size(x:Image.Image): return fastuple(_old_sz(x))
     27     Image._patched = True

TypeError: patch() got an unexpected keyword argument 'as_prop'
```
2. Run `from fastai.vision.all import *` (in terminal in gradient)

```
Python 3.8.5 | packaged by conda-forge | (default, Aug 21 2020, 18:21:27)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fastai.vision.all import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/fastai/lib/python3.8/site-packages/fastai/vision/all.py",line 1, in <module>
    from . import models
  File "/opt/conda/envs/fastai/lib/python3.8/site-packages/fastai/vision/models/__init__.py", line 1, in <module>
    from . import xresnet
  File "/opt/conda/envs/fastai/lib/python3.8/site-packages/fastai/vision/models/xresnet.py", line 12, in <module>
    from ...torch_basics import *
  File "/opt/conda/envs/fastai/lib/python3.8/site-packages/fastai/torch_basics.py", line 9, in <module>
    from .imports import *
  File "/opt/conda/envs/fastai/lib/python3.8/site-packages/fastai/imports.py", line 25, in <module>
    import requests,yaml,matplotlib.pyplot as plt,pandas as pd,scipy
  File "/opt/conda/envs/fastai/lib/python3.8/site-packages/scipy/__init__.py", line 155, in <module>
    from . import fft
  File "/opt/conda/envs/fastai/lib/python3.8/site-packages/scipy/fft/__init__.py", line 79, in <module>
    from ._helper import next_fast_len
  File "/opt/conda/envs/fastai/lib/python3.8/site-packages/scipy/fft/_helper.py",line 3, in <module>
    from ._pocketfft import helper as _helper
  File "/opt/conda/envs/fastai/lib/python3.8/site-packages/scipy/fft/_pocketfft/__init__.py", line 3, in <module>
    from .basic import *
  File "/opt/conda/envs/fastai/lib/python3.8/site-packages/scipy/fft/_pocketfft/basic.py", line 6, in <module>
    from . import pypocketfft as pfft
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /opt/conda/envs/fastai/lib/python3.8/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-38-x86_64-linux-gnu.so)
```

**Comment by kessido** [comment] 2020-11-07 22:16
Couldn't reproduce in collab using fastai==2.1.4 && fastcore==1.3.2
https://colab.research.google.com/drive/17rtkrGVnHh7ufczWWOnrECNe1LsfEzAB?usp=sharing

Might be problem with many python environments?

**Comment by tkravichandran** [comment] 2020-11-07 23:23
Why would that be the problem? and How can I test it? conda is "supposed to manage the packages" but looks like it (fastai) has been installed with `pip` (`conda list fastai` gives `channel` = `pypi`). There are three separate environments but the "fastai" environment is selected now.

And what about the error message? Does that say anything useful?

**Comment by hamelsmu** [comment] 2020-11-10 09:02
I'm not able to reproduce this error either

**Comment by hamelsmu** [comment] 2020-12-20 18:39
I've tested this and it doesnt' appear to be an issue anymore.  Closing this, but please feel to let me know if it is not resolved.  cc: @jph00

**Closed by hamelsmu** 2020-12-20 18:39 UTC
